### ISSUE TITLE
trouble connecting to wifi for 1.8.7

### ISSUE THREAD

**Issue by michmike** [death2all110/yi-hack#30] opened 2017-05-15 08:52 UTC
hi there,

i am fairly knowledgeable with tinkering gadgets like this camera, but i am having some trouble getting my Yi (US edition) model to connect to wifi.

My camera came with 1.8.7.0A firmware, which i see is the same major version of the firmware as the home file (i did a grep on the file)

My wifi characteristics are 
2.4Ghz, WPA2-Personal, AES encryption
I chose DHCP in the yi-hack.cfg file and let the cloud=yes option.

After trying a few options on the wpa_supplicant.conf, i still could not get it to work and the camera is stuck in the forever loop of "waiting to connect". There are no debug log files generated, although i did not enable the yi-hack.cfg option of debug=yes.
Prior to trying this out, i did RESET the camera and format the SD card to start clean. I followed the directions on the folder structure so that the root of the SD card has the "home" file and "test" folder.

here's two examples of the files i used.
`ctrl_interface=/var/run/wpa_supplicant
ap_scan=1
network={
ssid="m2Guests"
scan_ssid=1
proto=WPA RSN
key_mgmt=WPA-PSK
pairwise=CCMP
group=CCMP
psk="<my pwd>"
}`

`ctrl_interface=/var/run/wpa_supplicant
ap_scan=1
network={
ssid="m2Guests"
scan_ssid=1
proto=WPA RSN
key_mgmt=WPA-PSK
pairwise=CCMP TKIP
group=CCMP TKIP
psk="<my pwd>"
}`

As a last form of troubleshooting, while the camera had the SD card inserted and was in this loop of waiting to connect, i used the Yi app for android, and it was able to connect to wifi. however, even after that happened, i was not able to access the http://<my camera IP> address.

any help or advice is appreciated
thanks!

**Comment by raidenii** [comment] 2017-05-15 15:34
Which channel is your 2.4Ghz network on? My personal experience is that the camera only works great if the channel is on 1, 6 or 11. Pick a least crowded of the three and try to reconnect it.

**Comment by michmike** [comment] 2017-05-15 15:37
@raidenii that's a good point. i did not try that. let me give it a shot. i know a lot of folks had trouble with the 1.8.7 firmware, but that's because they were not using this particular fork of the firmware

**Comment by michmike** [comment] 2017-05-20 18:28
i tried it on channel 1 for my 2.4ghz and that did not work either. if i don't use the hack, the Yi connects to that same router just fine and i can see my video on the Yi app.

**Comment by death2all110** [comment] 2017-06-20 16:25
Duplicate of #29.

**Closed as completed by death2all110** 2017-06-20 16:25 UTC
Labels: duplicate
